### ISSUE TITLE
bug- error running yarn build

### ISSUE THREAD

**Issue by lgwapnitsky** [KnowledgeCanvas/knowledge-canvas#34]
successful yarn install.

yarn build produces the following:

```
knowledgecanvas:/opt/knowledge-canvas# yarn build
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)
```

**Comment by lgwapnitsky** [comment]
more details in attached file. FIrst 2 lines are nodejs and yarn versions

[kc_build.txt](https://github.com/KnowledgeCanvas/knowledge-canvas/files/8218802/kc_build.txt)

**Comment by RobRoyce** [comment]
Interesting. What OS? Did you follow the [instructions in the Wiki](https://github.com/KnowledgeCanvas/knowledge-canvas/wiki/Development#getting-started)?

**Comment by lgwapnitsky** [comment]
Ubuntu 20.04 and 21.10. Instructions followed to a tee

Fresh install on 20.04 this morning. Had to install a large number of extra libraries. Now battling electron SIGTRAP error on `yarn start`

**Comment by lgwapnitsky** [comment]
nevermind.  I've got it running now

**Comment by lgwapnitsky** [comment]
Ubuntu 20.04. Also tried 21.10

And,yes, instructions followed to a tee
